<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite.Core" />
    <PackageReference Include="SQLitePCLRaw.bundle_winsqlite3" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" />
    <PackageReference Include="Tomlyn" />
  </ItemGroup>
</Project>
